spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway.locations: db
  h2:
    console:
      enabled: true